model:
  trained_model_name: "local_ansunghun_01.pth"
  file_index: "C:/RVC/RVC_test/logs/local_ansunghun_01/added_IVF4058_Flat_nprobe_1_local_ansunghun_01_v2.index"

paths:
  input_audio: "C:/RVC/RVC_test/infer_song/local_infer_song.wav"
  first_mr_output_dir: "C:/RVC/RVC_test/first_mr_output"
  output_info: "C:/RVC/RVC_test/infer_output_log.txt"
  output_audio: "C:/RVC/RVC_test/infer_output/output_infer.wav"
  mixed_output: "C:/RVC/RVC_test/infer_output/mixed_output.wav"

inference:
  spk_id: 0
  transform: 0
  f0_file: null
  f0_method: "rmvpe"
  index_rate: 0.75
  filter_radius: 3
  resample_sr: 0
  rms_mix_rate: 0.25
  protect: 0.33
