model:
  trained_model_name: ""
  file_index: ""

paths:
  input_audio: ""
  first_mr_output_dir: ""
  output_info: ""
  output_audio: ""
  mixed_output: ""

inference:
  spk_id: 0
  transform: 0
  f0_file: null
  f0_method: "rmvpe"
  index_rate: 0.75
  filter_radius: 3
  resample_sr: 0
  rms_mix_rate: 0.25
  protect: 0.33
